index.html

Added discord invite link

---

README.md

Added some more details in readme.md file

---

README.md

- Added badges of MIT License and PRs welcome to readme, addresses [issue-22](https://github.com/JIITODC/jiitodc.github.io/issues/22)

added readme badges for MIT and PRs welcome

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Fixes #21
- Add issue template in the `.github/` directory
- Add PR template in the `.github/` directory

Add issue & PR templates. Fixes #21.

---

js/custom.js

Animate on scroll (AOS) library was not working so removed it.
Fixes #
-
-
-

Removed AOS.init

---

css/style.css

Fixes #
The problem with navbar has been fixed.
Also the navbar has been made a bit smalller to accomodate everything in a single line.

Fixed the problem with the navbar

---

css/style.css
index.html

Fixes #2 
- Use cards to list members
- Hover on card to flip card for more information
- Just a note that I've also fixed the indentation in **index.html** (it looks like there are lots of changes but they are just indentation)
_I'll be happy to update the list of members with the actual information if any of you guys can provide me with the list_. 😄

Add contributors section

---

css/style.css
index.html

Changes on top of #54 to address #2
- To make the flipping animation less laggy, only trigger the flip *upon click*
- Also added the whole list of current contributors
@Ankk98 have a look!

Make the flip animation faster for contributors

---

CONTRIBUTING.md
css/style.css
index.html

Fixes #41 
- Remove news from the navbar
-Contact occurs 2 times in navbar 
- Try having a menu in the centre of the page
- Remove news section from page
- There is a typo in Members section heading
-  Create alternate colour coding in the background of sections to differentiate sections
- In footer add Made by JODC and contributors

Fixed merge conflicts and Fixes #41

---

CONTRIBUTING.md
README.md
code-of-conduct.md

- Added Discord invite
- Updated contributing.md
- Added code of conduct

Updated Guidelines

---

css/style.css
index.html
js/custom.js

Fixes #60 
It's not exactly perfect on some of the obscure smaller screen sizes but it works on mobile and tablets.  The hamburger menu comes from Font Awesome since it was already being used.
Also, the hamburger only appears at 515px screen width and the nav is hidden here also.  If you'd like the nav hidden and the hamburger to appear at larger screen sizes (~715px) just let me know and I can change it.

Responsiveness + Hamburger

---

index.html

Added fork button to footer

---

css/style.css
index.html
js/custom.js

Fixes #82 
- Navbar transforms into a hamburger menu on screens with a width less than 1300 px

Make navbar responsive

---

index.html

Fixes #5 
Added info template for how we started section

Added info to the how we started section

---

index.html

**REFERENCING ISSUE #_**
Added some content
Verified, Merge

added some content

---

index.html

**REFERENCING ISSUE #_**
_A brief but clear explaination of the fixes that were applied by the author in this PR_
**Note that screenshots regarding the issue must be attached whenever possible**
_Any (additional) information that the author would like to provide about this PR_
_**PLEASE BE AWARE THAT ANY PRs NOT FOLLOWING THE AFOREMENTIONED FORMAT SHALL BE CLOSED IMMEDIATELY**_

Spelling and grammar

---

css/style.css
index.html

**REFERENCING ISSUE #3 **
I have added a timeline section to the events part of the website.
https://screenshots.firefox.com/rF5pkYLidBUmxYgc/null

Timeline Section Created

---

css/style.css

**REFERENCING ISSUE #81 **
For Changes info refer issue #88

Updated css file in reference with index.html

---

index.html

**REFERENCING ISSUE #88**
- Added Home icon in navbar
- Added interactive font awesome icons in home section
- Fixed problem with the position of hamburger menu in smaller screens (with width less than 1300px)
- Displayed Menu indication with hamburger icon in smaller screens
- fixed linting errors
Home Option in navbar
Interactive font-awesome icons in home option
Before edit: Navbar in mobile view not correctly aligned 
After edit: Navbar right aligned with Menu indication

Updated index.html to be more responsive

---

index.html

**REFERENCING ISSUE #9 and ISSUE #11  and ISSUE #91 **
- Added form to send suggestions to jodc email
- Added Jodc Logo 
Form to send suggestions
Logo

Added logo and form section to send suggestion

---

css/style.css

 Updated css file in reference with index.html

---

index.html

**REFERENCING ISSUE #3 **
Added details about the past and upcoming events.
Shot 1:
Shot 2:
Shot 3:

Added Events and set fork ribbon to be fixed
